apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: database
spec:
  compositeTypeRef:
    apiVersion: persistence.example.com/v1alpha1
    kind: SqlDb
  resources:
    - name: gcp-database
      base:
        apiVersion: sql.gcp.upbound.io/v1beta1
        kind: DatabaseInstance
        spec:
          forProvider:
            location: "US"
            databaseVersion: "POSTGRES_15"
            settings:
              tier: "db-f1-micro"
              diskAutoResizeLimit: 10
      patches:
        - fromFieldPath: "spec.location"
          toFieldPath: "spec.forProvider.location"
          transforms:
            - type: map
              map:
                EU: "EU"
                US: "US"
        - fromFieldPath: "spec.size"
          toFieldPath: "spec.forProvider.settings.diskSize"
